#!/usr/bin/env bash
set -Eeuo pipefail

sqlplus -s / as sysdba <<SQL
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON
SET VERIFY OFF

ALTER SESSION SET CONTAINER=FREEPDB1;

BEGIN
  FOR obj IN (
    SELECT TABLE_NAME AS OBJECT_NAME
      FROM DBA_TABLES
     WHERE OWNER = '${DB_SCHEMA_USER}'
  ) LOOP
    EXECUTE IMMEDIATE
      'GRANT SELECT, INSERT, UPDATE, DELETE ON ${DB_SCHEMA_USER}.'
      || DBMS_ASSERT.SIMPLE_SQL_NAME(obj.OBJECT_NAME)
      || ' TO ${DB_RUNTIME_ROLE}';
  END LOOP;

  FOR obj IN (
    SELECT VIEW_NAME AS OBJECT_NAME
      FROM DBA_VIEWS
     WHERE OWNER = '${DB_SCHEMA_USER}'
  ) LOOP
    EXECUTE IMMEDIATE
      'GRANT SELECT ON ${DB_SCHEMA_USER}.'
      || DBMS_ASSERT.SIMPLE_SQL_NAME(obj.OBJECT_NAME)
      || ' TO ${DB_RUNTIME_ROLE}';
  END LOOP;

  FOR obj IN (
    SELECT SEQUENCE_NAME AS OBJECT_NAME
      FROM DBA_SEQUENCES
     WHERE SEQUENCE_OWNER = '${DB_SCHEMA_USER}'
  ) LOOP
    EXECUTE IMMEDIATE
      'GRANT SELECT ON ${DB_SCHEMA_USER}.'
      || DBMS_ASSERT.SIMPLE_SQL_NAME(obj.OBJECT_NAME)
      || ' TO ${DB_RUNTIME_ROLE}';
  END LOOP;

  FOR obj IN (
    SELECT OBJECT_NAME
      FROM DBA_OBJECTS
     WHERE OWNER = '${DB_SCHEMA_USER}'
       AND OBJECT_TYPE IN ('PROCEDURE', 'FUNCTION', 'PACKAGE')
       AND STATUS = 'VALID'
  ) LOOP
    EXECUTE IMMEDIATE
      'GRANT EXECUTE ON ${DB_SCHEMA_USER}.'
      || DBMS_ASSERT.SIMPLE_SQL_NAME(obj.OBJECT_NAME)
      || ' TO ${DB_RUNTIME_ROLE}';
  END LOOP;
END;
/

PROMPT === Grants do usuário de aplicação atualizados ===
SELECT GRANTEE, GRANTED_ROLE
  FROM DBA_ROLE_PRIVS
 WHERE GRANTEE = '${DB_RUNTIME_USER}';

EXIT
SQL
